import "./globals.css";
import { Rubik } from "next/font/google";

// components

import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";


const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={rubik.className}>
				<Header />
				{children}
				<Footer/>
			</body>
		</html>
	);
}
